// @flow

export const DUMMY: "DUMMY" = "DUMMY";
export const SET_USER_ID: "SET_USER_ID" = "SET_USER_ID";
export const START_TRAINING: "START_TRAINING" = "START_TRAINING";
export const WRITE_ELEMENTS_TO_STATE: "WRITE_ELEMENTS_TO_STATE" =
  "WRITE_ELEMENTS_TO_STATE";
export const WRITE_PATTERN_TO_STATE: "WRITE_PATTERN_TO_STATE" =
  "WRITE_PATTERN_TO_STATE";
export const SELECT_ELEMENT: "SELECT_ELEMENT" = "SELECT_ELEMENT";
export const START_USER_INPUT: "START_USER_INPUT" = "START_USER_INPUT";
